### PR TITLE
add better non mtg game support

### PR DESCRIPTION
**Pull request by wsor4035**
see title, this also updates the mods readme file.

assuming approval and merging, dependabot support will be added shortly

### CODE REVIEW

**Comment by OgelGames** [comment]
Why is `sounds_api` a submodule and not just a dependency? 😕

**Comment by wsor4035** [comment]
> Why is `sounds_api` a submodule and not just a dependency? 😕 I don't think submodules are compatible with ContentDB. (zip download from github only has an empty folder for it)

because the point is to keep it up to date ourselves rather than dealing with version mismatches, etc. The second statement about contentdb not supporting submodule is entirely incorrecty. cdb does support http submodules, certain ssh submodules can be a issue. (source being cdb staff, my game on cdb having submodules and working fine).

**Comment by OgelGames** [comment]
> cdb does support http submodules, certain ssh submodules can be a issue.

Ah ok, good to know.

> do not want to tell users that they need a additionally mod just to have sounds already in there game.

Well that solution seems to have worked fine for other API mods, for example, [player_monoids](https://github.com/minetest-mods/player_monoids) and [fsc](https://github.com/sofar/fsc).

**Comment by wsor4035** [comment]
> > cdb does support http submodules, certain ssh submodules can be a issue.
> 
> Ah ok, good to know.
> 
> > do not want to tell users that they need a additionally mod just to have sounds already in there game.
> 
> Well that solution seems to have worked fine for other API mods, for example, [player_monoids](https://github.com/minetest-mods/player_monoids) and [fsc](https://github.com/sofar/fsc).

funny you sound mention fsc. lets look at cdb https://content.minetest.net/metapackages/fsc/ no one but the author uses it. and the package that uses it is equally dead. looking at player moniods (which has been forked to no end) https://content.minetest.net/metapackages/player_monoids/ it is mainly used as a api for games with some mods supporting it. see my comment about it being forked to no end. you have a classic xkcd competing standards there and have to make sure that your mod is compatible with them all, or specify a specific one. using a submodule circumvents this by just using having a specific version.

**Comment by S-S-X** [comment]
> using a submodule circumvents this by just using having a specific version.

This is not necessarily good thing at all but just another thing that has both sides and certainly not simply better way to do things.

Anyway, hard requirement to use submodule can be changed later if needed for any reason.
Also while going with submodule is not clearly improvement it also wont clearly make mod any worse but instead is just different way to do things switching to different dependency workflow and lifecycle management.

**Review by S-S-X — APPROVED** [review]
Basic stuff here looks good to me.
I guess protector and node_ownership were in optional dependencies just to say that protection mods are supported but were not actually used anywhere?

**Comment by S-S-X** [comment]
Still one thing but I guess that can be changed later too: dependencies are probably not needed for fl_stone, fl_trees or mcl_sounds.

Same for anything that is not actually used or overridden, reason why I'm mentioning this is that having minimal dependencies and all unnecessary dependencies removed allows other mods to depend on this mod easier if needed. Less troubles resolving weird unnecessary dependency cycles.

This might not be really important here but still something to think about.

**Comment by wsor4035** [comment]
> Basic stuff here looks good to me.
> I guess protector and node_ownership were in optional dependencies just to say that protection mods are supported but were not actually used anywhere?

Those where things i forgot to remove in the clean up code, they where used for the nightmare file

**Comment by wsor4035** [comment]
> Still one thing but I guess that can be changed later too: dependencies are probably not needed for fl_stone, fl_trees or mcl_sounds.
> 
> Same for anything that is not actually used or overridden, reason why I'm mentioning this is that having minimal dependencies and all unnecessary dependencies removed allows other mods to depend on this mod easier if needed. Less troubles resolving weird unnecessary dependency cycles.
> 
> This might not be really important here but still something to think about.

All optional dependencies are need or else minetest may error out. I know specifically the sounds are because i had a error for one of them when testing

**Pull request merged**
